AWSTemplateFormatVersion: '2010-09-09'
Description: 'Stack de infraestructura profesional para Lightpress - VPC, EC2 y S3'

Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/canonical/ubuntu/server/22.04/stable/current/amd64/hvm/ebs-gp2/ami-id'

Resources:
  # 1. Redes (Punto 3 de la rúbrica)
  LightpressVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: Lightpress-VPC-IaC

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref LightpressVPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref LightpressVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: Lightpress-Public-Subnet

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref LightpressVPC

  DefaultPublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet

  # 2. Almacenamiento (Punto 2 de la rúbrica)
  LightpressIaCBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "lightpress-iac-eduardo-final-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled

  # 3. Cómputo (Punto 2 de la rúbrica)
  LightpressIaCInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: !Ref LatestAmiId # <--- Ahora es automático y dinámico
      SubnetId: !Ref PublicSubnet
      IamInstanceProfile: Lightpress-EC2-Role
      Tags:
        - Key: Name
          Value: Lightpress-EC2-IaC
